In [ ]:
import functions
import pandas as pd
import numpy as np

C:\Users\franc\AppData\Roaming\Python\Python39\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [ ]:
df = pd.read_csv("original_data.csv")

In [ ]:
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df, test_size=0.2, random_state=0)
df_train= df_train.reset_index(drop=True) #to reset the indices
df_train

id                         movie_name  \
0      33697  Nativity 2: Danger in the Manger!   
1      16389                   The 300 Spartans   
2      11071                           Centauri   
3      18528    The 20 Questions Murder Mystery   
4      83072                            Bunjako   
...      ...                                ...   
43195  26489                        Sudden Fury   
43196  56086                 The World Gone Mad   
43197  86414                            La clef   
43198  19473                Song of the Streets   
43199  80686                            Dimland   

                                                synopsis      genre  
0      A worried new teacher has to juggle a pregnant...     family  
1      A small Army of Greeks spearheaded by three hu...  adventure  
2      After their satellite crash lands on Alpha Cen...  adventure  
3      BBC Radio's 20 Questions receives anonymous cl...      crime  
4      College Students get stuck in a haunted forest...   thriller  
...                                                  ...        ...  
43195  After a terrible car accident, a man makes sur...      crime  
43196  A district attorney and a reporter try to find...    mystery  
43197  One morning, Eric Vincent, a thirty-something ...   thriller  
43198  A gang of poverty-ridden juvenile delinquents ...      crime  
43199  In an attempt to shake off her melancholy, a y...      scifi  

[43200 rows x 4 columns]

In [ ]:
#see the useless sentences before removing
for i in range(len(df_train)):
    if (("plot" in df_train["synopsis"][i].lower()) and
        "under" in df_train["synopsis"][i] and
        "wraps" in df_train["synopsis"][i]):
        print(df_train["synopsis"][i])

Plot under wraps.
Plot kept under wraps.
Plot under wraps. The third film in the "28 Days Later" franchise.
Plot under wraps.
Plot kept under wraps.
Plot under wraps.
Plot kept under wraps.
Plot under wraps.
Plot kept under wraps.
Plot kept under wraps.
Plot kept under wraps.
Plot under wraps.
Plot kept under wraps.
Plot kept under wraps.
Plot kept under wraps. Fourth movie in the Captain America franchise.
Plot details are being kept under wraps.
Plot details are being kept under wraps.
Plot details kept under wraps.
Plot kept under wraps.
Plot kept under wraps. Described as sci-fi action-thriller about the scarcity of water.
Plot being kept under wraps.
Plots under wraps.
Plot kept under wraps.
Plot is under wraps.
Plot under wraps.
Social horror film - plot still under wraps
Plot currently kept under wraps through development.
Plot kept under wraps.
Plot kept under wraps.
Plot under wraps.
Plot under wraps
The plot is being kept under wraps. Production is currently under way.
Plot u

In [ ]:
#preprocessing
df_train, x_train = functions.preprocessing(df=df_train, remove_useless_sentences = True, tokenize=True, remove_one_characters=True, lemmatize=True, remove_stop_words=True)
x_train[1]

You chose: remove_useless_sentences = True, tokenize = True, remove_one_characters = True, lemmatize = True and remove_stop_words = True


['small',
 'army',
 'greek',
 'spearheaded',
 'spartan',
 'battle',
 'invading',
 'persian',
 'army']

In [ ]:
#check after the removing
for i in range(len(df_train)):
    if (("plot" in df_train["synopsis"][i].lower()) and
        "under" in df_train["synopsis"][i] and
        "wraps" in df_train["synopsis"][i]):
        print(df_train["synopsis"][i])

In [ ]:
#the signficant part is still here (third is removed because it is in STOP_WORDS)
for i in range(len(df_train)):
    # Check the conditions for the specific row
    if ("28 day later" in df_train["synopsis"][i].lower()):
        print(df_train["synopsis"][i])

film 28 day later franchise


In [ ]:
#preprocessing for the test
df_test, x_test = functions.preprocessing(df=df_test, remove_useless_sentences = True, tokenize=True, remove_one_characters=True, lemmatize=True, remove_stop_words=True)
x_test[1]

You chose: remove_useless_sentences = True, tokenize = True, remove_one_characters = True, lemmatize = True and remove_stop_words = True


['sathyavati',
 'great',
 'devotee',
 'santoshi',
 'maa',
 'narada',
 'decides',
 'test',
 'devotion',
 'face',
 'challenge',
 'life']

In [ ]:
#prints for the choice of the padding size
list_lengths = [len(sublist) for sublist in x_train]

#average length
average_length = sum(list_lengths) / len(list_lengths)

print("Average Length of Lists in x_train:", average_length)

#maximum length
max_length = max(list_lengths)

print("Maximum Length of Lists in x_train:", max_length)

#longer than 30
count_longer_than_30 = sum(1 for sublist in x_train if len(sublist) > 30)

print("Number of lists longer than 30 in x_train:", count_longer_than_30)

Average Length of Lists in x_train: 14.070208333333333
Maximum Length of Lists in x_train: 43
Number of lists longer than 30 in x_train: 57


In [ ]:
#function called with only the training
padded_train, tokenizer = functions.tokenizer_padding(x_train, max_length=30)
print(padded_train, len(tokenizer.word_index)) #len(tokenizer.word_index) is the vocab_size

[[5108   14  400 ...    0    0    0]
 [  51  184 1472 ...    0    0    0]
 [3696  339  126 ...    0    0    0]
 ...
 [1395 2608 3530 ...    0    0    0]
 [  64 2842 2374 ...    0    0    0]
 [ 114 2560 9204 ...    0    0    0]] 37075


In [ ]:
#function called with training and test
padded_train, padded_test, tokenizer = functions.tokenizer_padding(x_train=x_train, max_length=30, x_test=x_test)
print(padded_train, "\n\n", padded_test, len(tokenizer.word_index))

[[5108   14  400 ...    0    0    0]
 [  51  184 1472 ...    0    0    0]
 [3696  339  126 ...    0    0    0]
 ...
 [1395 2608 3530 ...    0    0    0]
 [  64 2842 2374 ...    0    0    0]
 [ 114 2560 9204 ...    0    0    0]] 

 [[    2   201  5593 ...     0     0     0]
 [  248  6370 18804 ...     0     0     0]
 [ 1947  7678   340 ...     0     0     0]
 ...
 [  481   618    62 ...     0     0     0]
 [   67   141  1957 ...     0     0     0]
 [   71 10261   300 ...     0     0     0]] 37075


In [ ]:
print(df_train["genre"])
y_train = functions.target_variable(df_train, "genre")
print(y_train)

0           family
1        adventure
2        adventure
3            crime
4         thriller
           ...    
43195        crime
43196      mystery
43197     thriller
43198        crime
43199        scifi
Name: genre, Length: 43200, dtype: object
[3 1 1 ... 9 2 8]


In [ ]:
print(df_test["genre"])
y_test = functions.target_variable(df_test, "genre")
print(y_test)

0        thriller
1         fantasy
2         mystery
3        thriller
4         romance
           ...   
10795     mystery
10796     romance
10797      horror
10798     romance
10799    thriller
Name: genre, Length: 10800, dtype: object
[9 4 6 ... 5 7 9]
